stages:
  generate:
    cmd: >
      python3 scripts/generate_dataset.py
      --input-path data/gutenberg_shakespeare.txt
      --output-path data/sentences
    deps:
      - scripts/generate_dataset.py
      - ./data/gutenberg_shakespeare.txt
    outs:
      - ./data/sentences

  fit_tokenizer:
    cmd: >
      python3 ./scripts/fit_tokenizer.py
      --input-path data/sentences
      --output-path data/tokenized
    params:
      - fit_tokenizer
    deps:
      - ./scripts/fit_tokenizer.py
      - ./data/sentences
    outs:
      - ./data/tokenized
      - ./outs/tokenizer

  train_model:
    cmd: >
      python3 ./scripts/train_model.py
      --input-path data/tokenized
      --model-output-path outs/model
      --artefacts-path outs/training_artefacts
    params:
      - train
    deps:
      - ./src/shakespeare/torch_model.py
      - ./scripts/train_model.py
      - ./data/tokenized
    outs:
      - ./outs/training_artefacts
      - ./outs/model

  generate_embeddings:
    cmd: >
      python3 scripts/generate_embeddings.py
      --model-path ./outs/model
      --input-path ./data/tokenized
      --output-path ./data/embedded
    deps:
      - ./outs/model
      - ./data/tokenized
    outs:
      - ./data/embedded

  train_sae:
    cmd: >
      python3 ./scripts/train_sae.py
      --dataset-path ./data/embedded
      --tokenizer-path ./outs/tokenizer
      --model-output-path ./outs/sae
    deps:
      - ./outs/model
    outs:
      - ./outs/sae
    params:
      - train_sae