stages:
  generate:
    cmd: >
      python3 scripts/generate_dataset.py
      --input-path data/gutenberg_shakespeare.txt
      --output-path data/sentences
    deps:
      - scripts/generate_dataset.py
      - ./data/gutenberg_shakespeare.txt
    outs:
      - ./data/sentences

  fit_tokenizer:
    cmd: >
      python3 ./scripts/fit_tokenizer.py
      --input-path data/sentences
      --output-path data/tokenized
    deps:
      - ./scripts/fit_tokenizer.py
      - ./data/sentences
    outs:
      - ./data/tokenized
      - ./outs/tokenizer

  train_model:
    cmd: >
      python3 ./scripts/train_model.py
      --input-path data/tokenized
      --model-output-path outs/model.pt
      --artefacts-path outs/training_artefacts
    deps:
      - ./src/shakespeare/torch_model.py
      - ./scripts/train_model.py
      - ./data/tokenized
    outs:
      - ./outs/training_artefacts
      - ./outs/model.pt
