generate:
  model_name: microsoft/deberta-v3-large

fit_tokenizer:
  vocab_size: 1024

train:
  batch_size: 64
  num_epochs: 100
  random_seed: 42
  learning_rate: 0.0001
  model_init_params:
    embed_dim: 384
    num_heads: 6
    num_decoder_layers: 6
    ffn_dim: 1024
    max_seq_len: 512
    dropout: 0.1
    use_custom_pos_enc: true
    use_custom_transformer: true

train_sae:
  batch_size: 64
  num_epochs: 50
  learning_rate: 0.0001
  random_seed: 42
  model_init_params:
    hidden_dim: 4096
    top_k: 5
